### ISSUE TITLE
Crash while using chopsticks with calamari

### ISSUE THREAD

**Issue by Dengjianping** [Manta-Network/Manta#1293]
Bryan tried to send xcm transactions with tool chopsticks, but a crash happened:
```
INFO (block-builder/62570): Try building block #5,298,060
    app: "chopsticks"
    number: 5298060
    extrinsicsCount: 1
    umpCount: 0
runtime                      ERROR: panicked at 'Block invalid, supplied author is not eligible.', /home/builder/cargo/git/checkouts/nimbus-43d01ec6e06cfb96/a4775e8/pallets/author-inherent/src/lib.rs:133:13
[16:46:16.466] WARN (block-builder/62570): Failed to apply inherents {} Error: wasm unreachable instruction executed
    app: "chopsticks"
/Users/qiweiyang/GitHub/chopsticks/packages/core/dist/esm/blockchain/block-builder.js:142
            throw new Error('Failed to apply inherents');
                  ^

Error: Failed to apply inherents
    at initNewBlock (/Users/qiweiyang/GitHub/chopsticks/packages/core/dist/esm/blockchain/block-builder.js:135:19)
    at Module.buildBlock (/Users/qiweiyang/GitHub/chopsticks/packages/core/dist/esm/blockchain/block-builder.js:240:33)
    at TxPool.#buildBlock (/Users/qiweiyang/GitHub/chopsticks/packages/core/dist/esm/blockchain/txpool.js:188:47)
    at TxPool.#buildBlockIfNeeded (/Users/qiweiyang/GitHub/chopsticks/packages/core/dist/esm/blockchain/txpool.js:170:13)
```

We probably need and have to support chopsticks in the future, it's very convenient to test xcm and sibling chains.

**Comment by Dengjianping** [comment]
fixed
