### ISSUE TITLE
`--relay-chain-rpc-urls` doesn't work in docker containers

### ISSUE THREAD

**Issue by anaye1997** [Manta-Network/Manta#1318]
# Overview
adding `--relay-chain-rpc-urls` to manta docker container runs into issue
```bash
Thread 'main' panicked at 'Genesis block hash is always available; qed: RpcCallError("chain_getBlockHash")', /home/runner/.cargo/git/checkouts/cumulus-59522f43471fa161/b8999fc/client/relay-chain-minimal-node/src/lib.rs:139
```

![image](https://github.com/Manta-Network/Manta/assets/134174965/6643f312-0807-4f22-b41f-7e1ba0ede3f1)

## Reproduce

* start shell in manta docker container
```bash
#!/usr/bin/env bash

docker run \
  -it \
  --rm \
  -p 9933:9933 \
  -p 9934:9934 \
  -p 9944:9944 \
  -p 9945:9945 \
  -p 30333:30333 \
  -p 30334:30334 \
  -v ./data:/container_path \
  --name your_container_name \
  --entrypoint /bin/bash \
  mantanetwork/manta:v4.6.1
  ```

* start `manta` with ` --relay-chain-rpc-urls 'wss://polkadot.api.onfinality.io/public-ws'`
```bash
root@7cc690571d2c:/# manta --base-path /container_path/data   --chain manta   --keystore-path /container_path/keystore   --name debug_test   --rpc-cors all   --collator   --rpc-methods=safe   --relay-chain-rpc-urls 'wss://polkadot.api.onfinality.io/public-ws'   --relay-chain-rpc-urls 'wss://rpc.ibp.network/polkadot'   --   --telemetry-url 'wss://api.telemetry.manta.systems/submit/ 0'
2024-03-03 01:20:54 id:manta
2024-03-03 01:20:54 Manta/Calamari Collator
2024-03-03 01:20:54 ✌️  version 4.6.1-7ba8e7cf6cc
2024-03-03 01:20:54 ❤️  by Manta Network, 2020-2024
2024-03-03 01:20:54 📋 Chain specification: Manta Parachain
2024-03-03 01:20:54 🏷  Node name: debug_test
2024-03-03 01:20:54 👤 Role: AUTHORITY
2024-03-03 01:20:54 💾 Database: RocksDb at /container_path/data/chains/manta/db/full
2024-03-03 01:20:54 ⛓  Native runtime: manta-4610 (manta-1.tx7.au1)
2024-03-03 01:20:57 Parachain id: Id(2104)
2024-03-03 01:20:57 Parachain Account: 5Ec4AhNxUwx82DnzbYuEUF9jq4yo5yZUTkCd9iC8L9TRhRhW
2024-03-03 01:20:57 Parachain genesis state: 0x0000000000000000000000000000000000000000000000000000000000000000003bce487d1effd752b3ce68d8670cc28ac2acf59cb25dfafe52d0d6b3a7474c4803170a2e7597b7b7e3d84c05391d139a62b157e78786d8c082f29dcf4c11131400
2024-03-03 01:20:57 Is collating: yes
2024-03-03 01:20:57 [Parachain] Trying to connect to next external relaychain node. index=0 url="wss://polkadot.api.onfinality.io:443/public-ws"
2024-03-03 01:20:57 [Parachain] Trying to connect to next external relaychain node. index=1 url="wss://rpc.ibp.network:443/polkadot"
2024-03-03 01:20:57 [Parachain] No valid RPC url found. Stopping RPC worker.
2024-03-03 01:20:57 [Parachain] Essential task `relay-chain-rpc-worker` failed. Shutting down service.

====================

Version: 4.6.1-7ba8e7cf6cc

   0: <unknown>
   1: <unknown>
   2: <unknown>
   3: <unknown>
   4: <unknown>
   5: <unknown>
   6: <unknown>
   7: <unknown>
   8: <unknown>
   9: <unknown>
  10: <unknown>
  11: <unknown>
  12: <unknown>
  13: <unknown>
  14: <unknown>
  15: <unknown>
  16: <unknown>
  17: __libc_start_main
  18: <unknown>


Thread 'main' panicked at 'Genesis block hash is always available; qed: RpcCallError("chain_getBlockHash")', /home/runner/.cargo/git/checkouts/cumulus-59522f43471fa161/b8999fc/client/relay-chain-minimal-node/src/lib.rs:139

This is a bug. Please report it at:

        https://github.com/Manta-Network/Manta/issues/new
```

**Comment by anaye1997** [comment]
issue is related to outdated `ca` in the `v4.6.1` manta docker image, current workaround is to mount local ca path the to the container

```bash
-v /usr/share/ca-certificates:/usr/share/ca-certificates:ro \
-v /etc/ssl/certs:/etc/ssl/certs:ro \
```
