### ISSUE TITLE
Panic: Storage root must match that calculated.

### ISSUE THREAD

**Issue by nazar-pc** [Manta-Network/Manta#231]
I was syncing archival node using this docker-compose.yml:
```yml
version: '2'

services:
  calamari:
    image: mantanetwork/calamari
    ports:
      - 19951:9944
    volumes:
      - ./calamari:/data
    entrypoint: /usr/local/bin/parachain
    command: [
      "--base-path", "/data",
      "--chain", "calamari",
      "--pruning", "archive",
      "--ws-external",
      "--rpc-external",
      "--rpc-cors", "all",
      "--bootnodes", "/dns/crispy.calamari.systems/tcp/30333/p2p/12D3KooWNE4LBfkYB2B7D4r9vL54YMMGsfAsXdkhWfBw8VHJSEQc",
    ]
```

And at certain point it started printing panics (attaching small snippet, it repeats over and over again) suggesting me to report bug, so here I am:

<details>

```
calamari_1  | 2021-10-26 21:01:56 [Parachain] ✨ Imported #263992 (0x9d26…d667)    
calamari_1  | 2021-10-26 21:01:56 [Parachain] ♻️  Reorg on #263992,0x9d26…d667 to #263774,0x524d…1bb7, common ancestor #263773,0xc603…155a    
calamari_1  | 2021-10-26 21:01:56 [Parachain] ✨ Imported #263774 (0x524d…1bb7)    
calamari_1  | 2021-10-26 21:01:57 [Parachain] 💤 Idle (10 peers), best: #263774 (0x524d…1bb7), finalized #0 (0x4ac8…17a1), ⬇ 1.4kiB/s ⬆ 1.0kiB/s    
calamari_1  | 2021-10-26 21:01:57 [Relaychain] ⚙️  Syncing 14.5 bps, target=#9827644 (50 peers), best: #7350302 (0x6b84…63af), finalized #7350272 (0xf100…ee68), ⬇ 102.7kiB/s ⬆ 73.8kiB/s    
calamari_1  | 2021-10-26 21:01:58 [Relaychain] 🔍 Discovered new external address for our node: /ip4/172.17.0.3/tcp/30334/ws/p2p/12D3KooWAsLFgDYsXCA2FVcpnMDTzd9YziQYa4W1fM7Y5wPKpruh    
calamari_1  | 2021-10-26 21:01:58 [Parachain] ♻️  Reorg on #263774,0x524d…1bb7 to #263986,0xe2fd…8153, common ancestor #263773,0xc603…155a    
calamari_1  | 2021-10-26 21:01:58 [Parachain] ✨ Imported #263986 (0xe2fd…8153)    
calamari_1  | 2021-10-26 21:01:59 [Parachain] ♻️  Reorg on #263986,0xe2fd…8153 to #263993,0xd0a1…cf97, common ancestor #263985,0x8775…8bff    
calamari_1  | 2021-10-26 21:01:59 [Parachain] ✨ Imported #263993 (0xd0a1…cf97)    
calamari_1  | 2021-10-26 21:02:00 [Parachain] ⚠️ System declares internal migrations (which *might* execute). On-chain `StorageVersion(0)` vs current storage version `StorageVersion(0)`    
calamari_1  | 2021-10-26 21:02:00 [Parachain] ✅ no migration for Sudo    
calamari_1  | 2021-10-26 21:02:00 [Parachain] ✅ no migration for Multisig    
calamari_1  | 2021-10-26 21:02:00 [Parachain] ✅ no migration for Utility    
calamari_1  | 2021-10-26 21:02:00 [Parachain] ✅ no migration for DmpQueue    
calamari_1  | 2021-10-26 21:02:00 [Parachain] ✅ no migration for CumulusXcm    
calamari_1  | 2021-10-26 21:02:00 [Parachain] ⚠️ PolkadotXcm declares internal migrations (which *might* execute). On-chain `StorageVersion(0)` vs current storage version `StorageVersion(0)`    
calamari_1  | 2021-10-26 21:02:00 [Parachain] ✅ no migration for XcmpQueue    
calamari_1  | 2021-10-26 21:02:00 [Parachain] ✅ no migration for AuraExt    
calamari_1  | 2021-10-26 21:02:00 [Parachain] ✅ no migration for Aura    
calamari_1  | 2021-10-26 21:02:00 [Parachain] ✅ no migration for Session    
calamari_1  | 2021-10-26 21:02:00 [Parachain] ✅ no migration for CollatorSelection    
calamari_1  | 2021-10-26 21:02:00 [Parachain] ✅ no migration for Authorship    
calamari_1  | 2021-10-26 21:02:00 [Parachain] ✅ no migration for TransactionPayment    
calamari_1  | 2021-10-26 21:02:00 [Parachain] ✅ no migration for Balances    
calamari_1  | 2021-10-26 21:02:00 [Parachain] ✅ no migration for ParachainInfo    
calamari_1  | 2021-10-26 21:02:00 [Parachain] ✅ no migration for Timestamp    
calamari_1  | 2021-10-26 21:02:00 [Parachain] ✅ no migration for ParachainSystem    
calamari_1  | Hash: given=757f1ac547665205ea74bad11c76fa2ada6db0dd600900856f4927f7844771a7, expected=df64ae0fef327a30bb3872327c533cc23107ea9c2c986312f0d57fdf25f051f9
calamari_1  | 
calamari_1  | ====================
calamari_1  | 
calamari_1  | Version: 3.0.6-b7b293f-x86_64-linux-gnu
calamari_1  | 
calamari_1  |    0: <unknown>
calamari_1  |    1: <unknown>
calamari_1  |    2: <unknown>
calamari_1  |    3: <unknown>
calamari_1  |    4: <unknown>
calamari_1  |    5: <unknown>
calamari_1  |    6: <unknown>
calamari_1  |    7: <unknown>
calamari_1  |    8: <unknown>
calamari_1  |    9: <unknown>
calamari_1  |   10: <unknown>
calamari_1  |   11: <unknown>
calamari_1  |   12: <unknown>
calamari_1  |   13: <unknown>
calamari_1  |   14: <unknown>
calamari_1  |   15: <unknown>
calamari_1  |   16: <unknown>
calamari_1  |   17: <unknown>
calamari_1  |   18: <unknown>
calamari_1  |   19: <unknown>
calamari_1  |   20: <unknown>
calamari_1  |   21: <unknown>
calamari_1  |   22: <unknown>
calamari_1  |   23: <unknown>
calamari_1  |   24: <unknown>
calamari_1  |   25: <unknown>
calamari_1  |   26: <unknown>
calamari_1  |   27: <unknown>
calamari_1  |   28: <unknown>
calamari_1  |   29: <unknown>
calamari_1  |   30: <unknown>
calamari_1  |   31: <unknown>
calamari_1  |   32: <unknown>
calamari_1  |   33: <unknown>
calamari_1  |   34: <unknown>
calamari_1  |   35: <unknown>
calamari_1  |   36: <unknown>
calamari_1  |   37: <unknown>
calamari_1  |   38: <unknown>
calamari_1  |   39: <unknown>
calamari_1  |   40: start_thread
calamari_1  |   41: clone
calamari_1  | 
calamari_1  | 
calamari_1  | Thread 'tokio-runtime-worker' panicked at 'Storage root must match that calculated.', /home/runner/.cargo/git/checkouts/substrate-7e08433d4c370a21/9ee94fa/frame/executive/src/lib.rs:503
calamari_1  | 
calamari_1  | This is a bug. Please report it at:
calamari_1  | 
calamari_1  | 	https://github.com/Manta-Network/Manta/issues/new
calamari_1  | 
calamari_1  | 2021-10-26 21:02:00 [Parachain] ⚠️ System declares internal migrations (which *might* execute). On-chain `<wasm:stripped>` vs current storage version `<wasm:stripped>`    
calamari_1  | 2021-10-26 21:02:00 [Parachain] ✅ no migration for Sudo    
calamari_1  | 2021-10-26 21:02:00 [Parachain] ✅ no migration for Multisig    
calamari_1  | 2021-10-26 21:02:00 [Parachain] ✅ no migration for Utility    
calamari_1  | 2021-10-26 21:02:00 [Parachain] ✅ no migration for DmpQueue    
calamari_1  | 2021-10-26 21:02:00 [Parachain] ✅ no migration for CumulusXcm    
calamari_1  | 2021-10-26 21:02:00 [Parachain] ✅ no migration for PolkadotXcm    
calamari_1  | 2021-10-26 21:02:00 [Parachain] ✅ no migration for XcmpQueue    
calamari_1  | 2021-10-26 21:02:00 [Parachain] ✅ no migration for AuraExt    
calamari_1  | 2021-10-26 21:02:00 [Parachain] ✅ no migration for Aura    
calamari_1  | 2021-10-26 21:02:00 [Parachain] ✅ no migration for Session    
calamari_1  | 2021-10-26 21:02:00 [Parachain] ✅ no migration for CollatorSelection    
calamari_1  | 2021-10-26 21:02:00 [Parachain] ✅ no migration for Authorship    
calamari_1  | 2021-10-26 21:02:00 [Parachain] ✅ no migration for TransactionPayment    
calamari_1  | 2021-10-26 21:02:00 [Parachain] ✅ no migration for Balances    
calamari_1  | 2021-10-26 21:02:00 [Parachain] ✅ no migration for ParachainInfo    
calamari_1  | 2021-10-26 21:02:00 [Parachain] ✅ no migration for Timestamp    
calamari_1  | 2021-10-26 21:02:00 [Parachain] ✅ no migration for ParachainSystem    
calamari_1  | Hash: given=a64cd3e5f257258986246c3a7a5f431bdc682091730ba914b9d65ea288ef636d, expected=4515e80b7f767ec7b4ac725f904e9957bf4aac388730d629fcc744e7788563dc
calamari_1  | 
calamari_1  | ====================
calamari_1  | 
calamari_1  | Version: 3.0.6-b7b293f-x86_64-linux-gnu
calamari_1  | 
calamari_1  |    0: <unknown>
calamari_1  |    1: <unknown>
calamari_1  |    2: <unknown>
calamari_1  |    3: <unknown>
calamari_1  |    4: <unknown>
calamari_1  |    5: <unknown>
calamari_1  |    6: <unknown>
calamari_1  |    7: <unknown>
calamari_1  |    8: <unknown>
calamari_1  |    9: <unknown>
calamari_1  |   10: <unknown>
calamari_1  |   11: <unknown>
calamari_1  |   12: <unknown>
calamari_1  |   13: <unknown>
calamari_1  |   14: <unknown>
calamari_1  |   15: <unknown>
calamari_1  |   16: <unknown>
calamari_1  |   17: <unknown>
calamari_1  |   18: <unknown>
calamari_1  |   19: <unknown>
calamari_1  |   20: <unknown>
calamari_1  |   21: <unknown>
calamari_1  |   22: <unknown>
calamari_1  |   23: <unknown>
calamari_1  |   24: <unknown>
calamari_1  |   25: <unknown>
calamari_1  |   26: <unknown>
calamari_1  |   27: <unknown>
calamari_1  |   28: <unknown>
calamari_1  |   29: <unknown>
calamari_1  |   30: <unknown>
calamari_1  |   31: <unknown>
calamari_1  |   32: <unknown>
calamari_1  |   33: <unknown>
calamari_1  |   34: <unknown>
calamari_1  |   35: <unknown>
calamari_1  |   36: <unknown>
calamari_1  |   37: <unknown>
calamari_1  |   38: <unknown>
calamari_1  |   39: <unknown>
calamari_1  |   40: start_thread
calamari_1  |   41: clone
calamari_1  | 
calamari_1  | 
calamari_1  | Thread 'tokio-runtime-worker' panicked at 'Storage root must match that calculated.', /home/runner/.cargo/git/checkouts/substrate-7e08433d4c370a21/9ee94fa/frame/executive/src/lib.rs:503
calamari_1  | 
calamari_1  | This is a bug. Please report it at:
calamari_1  | 
calamari_1  | 	https://github.com/Manta-Network/Manta/issues/new
calamari_1  | 
calamari_1  | Hash: given=a19d4d686d6178e510b52e47d85ae060f1af7f28d51f87ee792eb8f475faa652, expected=320fc845300b2d578a45d2963ba91f199f3c5498f3c5afbedfb77eb80c4c5411
calamari_1  | 
calamari_1  | ====================
```

</details>

**Comment by Dengjianping** [comment]
Thanks for reporting this problem!

It crashed while runtime upgrade, actually. And current manta image is using this chain spec `--chain=calamari`, we will replace it with a chain spec file. Hopefully, it didn't cause by it.

Anyway, we will look into it. Thanks again!

**Comment by stechu** [comment]
@nazar-pc  this is due to the the same spec version but different implementation in the current running node and `v3.0.6`. We are going to release `v3.0.7` soon and this should not be a problem at more.

**Comment by Dengjianping** [comment]
If you use the latest image, the problem will not happen to you @nazar-pc .
I'm going to close it. Any question or problem is welcomed.
